config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :accounts
  resources :suppliers
  resources :books
  resources :authors
  resources :contacts
  get 'trainings/ror'

  get 'trainings/cucumber'

  get 'contacts/your_contact'

  get '/my_contact' => 'contacts#my_contact'

  get 'online_jobs/ror'

  get 'online_jobs/cucumber'

  root to: 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
   belongs_to  :supplier, :foreign_key => "supplier_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
   belongs_to :doctor, :foreign_key => "doctor_id"
   belongs_to :patient, :foreign_key => "patient_id"
end

app/models/author.rb
class Author < ApplicationRecord
  has_one :book
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, foreign_key: "author_id"
end

app/models/contact.rb
class Contact < ApplicationRecord
#validations
#associations
#class_methods
#callbacks
validates :name, :email, :cell, :gender, :address, presence: true
validates :cell, numericality: { only_integer: true }
validates :cell, length: { is: 10 }
#after_create :send_mails
def send_mails
 UserMailer.registration_confirmation(self).deliver
end

end

app/models/contact_observer.rb
class ContactObserver < ActiveRecord::Observer
  observe Contact
  
  def after_create(contact)
	UserMailer.registration_confirmation(contact).deliver
  end
  
  def before_create(contact)
    contact.name.capitalize!
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
   has_many :appointments
   has_many :patients, :through => :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
   has_many :appointments
   has_many :doctors, :through => :appointments
end

app/models/supplier.rb
class Supplier < ApplicationRecord
   has_one :account
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.dob
    "27-05-1975"
  end
  My_full_name = "M Srinivas"
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/online_jobs_helper.rb
module OnlineJobsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :doctor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<% @doctor.patients.each do |pat| %>
   <%= pat.name %>
<% end %>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>