config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :accounts
  resources :suppliers
  resources :books
  resources :authors
  resources :contacts
  get 'trainings/ror'

  get 'trainings/cucumber'

  get 'contacts/your_contact'

  get '/my_contact' => 'contacts#my_contact'

  get 'online_jobs/ror'

  get 'online_jobs/cucumber'

  root to: 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
   belongs_to  :supplier, :foreign_key => "supplier_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
   belongs_to :doctor, :foreign_key => "doctor_id"
   belongs_to :patient, :foreign_key => "patient_id"
end

app/models/author.rb
class Author < ApplicationRecord
  has_one :book
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, foreign_key: "author_id"
end

app/models/contact.rb
class Contact < ApplicationRecord
#validations
#associations
#class_methods
#callbacks
validates :name, :email, :cell, :gender, :address, presence: true
validates :cell, numericality: { only_integer: true }
validates :cell, length: { is: 10 }
#after_create :send_mails
def send_mails
 UserMailer.registration_confirmation(self).deliver
end

end

app/models/contact_observer.rb
class ContactObserver < ActiveRecord::Observer
  observe Contact
  
  def after_create(contact)
	UserMailer.registration_confirmation(contact).deliver
  end
  
  def before_create(contact)
    contact.name.capitalize!
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
   has_many :appointments
   has_many :patients, :through => :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
   has_many :appointments
   has_many :doctors, :through => :appointments
end

app/models/supplier.rb
class Supplier < ApplicationRecord
   has_one :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:supplier_id, :account_type, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.dob
    "27-05-1975"
  end
  My_full_name = "M Srinivas"
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/online_jobs_helper.rb
module OnlineJobsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.text_field :supplier_id, id: :account_supplier_id %>
  </div>

  <div class="field">
    <%= form.label :account_type %>
    <%= form.text_field :account_type, id: :account_account_type %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance, id: :account_balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Account type</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.supplier_id %></td>
        <td><%= account.account_type %></td>
        <td><%= account.balance %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @account.supplier_id %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @account.account_type %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<p>
  <strong>Name:</strong>
  <%= @account.supplier.name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>